name: release
on:
  workflow_call:
    inputs:
      dockerfile_location:
        description: 'location of the dockerfile'
        type: string
        default: 'Dockerfile'
      platforms:
        description: 'platforms to build for'
        type: string
        default: 'linux/amd64,linux/arm/v7,linux/arm64/v8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker buildx build \
          -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${GITHUB_REF#refs/*/} \
          -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
          -f ${{ inputs.dockerfile_location }} \
          --push \
          --platform=${{ inputs.platforms }} \
          .